name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Login to DockerHub
        uses: docker/login-action@v1
=======
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Build Docker image
        run: |
          docker build -t my-image .
          docker tag my-image:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest

      - name: Log in to DockerHub
        uses: docker/login-action@v2
>>>>>>> 77ec56d (Inicializando repositorio con el proyecto)
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

<<<<<<< HEAD
      - name: Build, tag, and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-java-app
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

  test:
    runs-on: ubuntu-latest
    needs: build
=======
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-image:latest

  test:
    runs-on: ubuntu-latest
>>>>>>> 77ec56d (Inicializando repositorio con el proyecto)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
<<<<<<< HEAD
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Run tests with Maven
        run: mvn test
=======
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  
          java-version: '17'

      - name: Run tests with Maven
        run: mvn test
>>>>>>> 77ec56d (Inicializando repositorio con el proyecto)
